---
title: "Analysis of Pollution in United States (2016)"
author: "Sarah Lee, Aayush Aggarwal, Albert Sadiku, Alexander Marcozzi"
date: "Due: Monday, December 15 by 11:30 PM CT"
output:
  prettydoc::html_pretty:
    theme: architect
    toc: true
---

# Introduction

## Why Is This Important?

Pollution is one of the leading causes of global warming; hence, it is important to analyze the factors behind it to minimize and control it. Since the United States is one of the world’s biggest industrial and commercial nations, we chose this EPA sourced dataset that measures the effect of 4 different pollutants in the country: NO2, O3, SO2, and CO. Due to time constraints and the scope of this class (STAT 420), we decided to focus mainly on the CO2 levels.


## Description

This project focuses on pollution in the U.S. The file includes emission data from cities and towns around the country across multiple days and years, though we have chosen to focus on 2016 specifically. The variables include location information, such as state, city, and county, along with pollution information such as the amount of various greenhouse gasses emitted such as NO2, CO2, SO2, and O3. In total, there are 24 variables that actually contain data, and there are 6151 observations after cleaning duplicate entries and taking just the 2016 data. We will be attempting to create a model with CO.Mean as the response.

## Background Information of Our Dataset

Original link: [https://www.kaggle.com/sogun3/uspollution]

The data is originally sourced from EPA, but the organized .CSV file was shared on Kaggle.


## Note About Our Cleaned Dataset

The original dataset had two sets of duplicated measurements each day, the only difference being the CO measurements (the last 3 columns on the original data). The first set of duplicates had a value for ‘CO.AQI’ and the other duplicated set did not (marked as ‘NA’). To keep the data consistent, we removed the second duplicated set that had the 'NA' - ultimately, cleaning the dataset so there's only one recorded data point that's present per day. We will also remove certain unnecessary variables and entries that are missing data or/and are not needed for this analysis. 



# Methods


# Results


# Discussion 

# Apendix

